### ISSUE TITLE
Errors out when trying to run migrate command on an actual server

### ISSUE THREAD

**Issue by joshuatuscan** [UCSoftware/responsive-pulse#1]
https://www.dropbox.com/s/3ojtcqs691yp4zg/Screenshot%202015-08-06%2015.36.15.png?dl=0

**Comment by joshuatuscan** [comment]
Would love to use this software, but having a terrible time getting it running on our domain. Sort of got it running locally, but there seems to be some issues with mongo permissions.

**Comment by joshuatuscan** [comment]
When I try and actually run the site, I hit this error:

[gulp] [nodemon] starting `node app.js`
Server started, listening on 0.0.0.0:8123
MongoError: not authorized for query on ucros_development.sessions
    at Function.MongoError.create (/home/friendsllc/bff.co/pulse/node_modules/express-session-mongo/node_modules/mongodb/node_modules/mongodb-core/lib/error.js:31:11)
    at queryCallback (/home/friendsllc/bff.co/pulse/node_modules/express-session-mongo/node_modules/mongodb/node_modules/mongodb-core/lib/cursor.js:267:34)
    at Callbacks.emit (/home/friendsllc/bff.co/pulse/node_modules/express-session-mongo/node_modules/mongodb/node_modules/mongodb-core/lib/topologies/server.js:95:3)
    at null.messageHandler (/home/friendsllc/bff.co/pulse/node_modules/express-session-mongo/node_modules/mongodb/node_modules/mongodb-core/lib/topologies/server.js:243:23)
    at Socket.<anonymous> (/home/friendsllc/bff.co/pulse/node_modules/express-session-mongo/node_modules/mongodb/node_modules/mongodb-core/lib/connection/connection.js:262:22)
    at Socket.emit (events.js:107:17)
    at readableAddChunk (_stream_readable.js:163:16)
    at Socket.Readable.push (_stream_readable.js:126:10)
    at TCP.onread (net.js:529:20)

**Comment by joshuatuscan** [comment]
I've actually figured this part out on my own.
